import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";
import { fonts } from "@/fonts";
import { ReactQueryProvider } from "@/lib/react-query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <body suppressHydrationWarning={true}>
        <ChakraProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
